// <auto-generated />
using System;
using MealPrepPlanner.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace MealPrepPlanner.Dal.Migrations
{
    [DbContext(typeof(MealPrepDbContext))]
    [Migration("20260812222324_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MealPrepPlanner.Dal.Entities.Audit.AiExecutionLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("agent_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("Model")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt");

                    b.Property<string>("Response")
                        .HasColumnType("text")
                        .HasColumnName("response");

                    b.Property<int?>("TokensUsed")
                        .HasColumnType("integer")
                        .HasColumnName("tokens_used");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id")
                        .HasName("pk_ai_execution_logs");

                    b.HasIndex("WorkflowId")
                        .HasDatabaseName("ix_ai_execution_logs_workflow_id");

                    b.HasIndex("AgentName", "CreatedAt")
                        .HasDatabaseName("ix_ai_execution_logs_agent_name_created_at");

                    b.ToTable("ai_execution_logs", (string)null);
                });

            modelBuilder.Entity("MealPrepPlanner.Dal.Entities.Audit.DecisionEventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("actor_name");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("actor_type");

                    b.Property<string>("DecisionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("decision_type");

                    b.Property<string>("InputContext")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("input_context")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("OutputDecision")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("output_decision")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<long?>("ParentDecisionId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_decision_id");

                    b.Property<string>("Reasoning")
                        .HasColumnType("text")
                        .HasColumnName("reasoning");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_number");

                    b.Property<DateTimeOffset>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id")
                        .HasName("pk_decision_events");

                    b.HasIndex("InputContext")
                        .HasDatabaseName("ix_decision_events_input_context");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("InputContext"), "gin");

                    b.HasIndex("OutputDecision")
                        .HasDatabaseName("ix_decision_events_output_decision");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("OutputDecision"), "gin");

                    b.HasIndex("ParentDecisionId")
                        .HasDatabaseName("ix_decision_events_parent_decision_id");

                    b.HasIndex("WorkflowId")
                        .HasDatabaseName("ix_decision_events_workflow_id");

                    b.HasIndex("ActorName", "Timestamp")
                        .HasDatabaseName("ix_decision_events_actor_name_timestamp");

                    b.HasIndex("WorkflowId", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_decision_events_workflow_id_sequence_number");

                    b.ToTable("decision_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_decision_events_actor_type", "\"actor_type\" IN ('USER','AI_AGENT','BACKEND_SERVICE')");
                        });
                });

            modelBuilder.Entity("MealPrepPlanner.Dal.Entities.MealPlanning.MealPlanEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<string>("NutritionSummary")
                        .HasColumnType("jsonb")
                        .HasColumnName("nutrition_summary");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("draft")
                        .HasColumnName("status");

                    b.Property<int?>("TotalCookingTimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("total_cooking_time_minutes");

                    b.Property<decimal?>("TotalEstimatedCost")
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("total_estimated_cost");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.Property<DateOnly>("WeekStartDate")
                        .HasColumnType("date")
                        .HasColumnName("week_start_date");

                    b.Property<Guid?>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_meal_plans");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_meal_plans_status");

                    b.HasIndex("HouseholdId", "WeekStartDate")
                        .HasDatabaseName("ix_meal_plans_household_id_week_start_date");

                    b.ToTable("meal_plans", (string)null);
                });

            modelBuilder.Entity("MealPrepPlanner.Dal.Entities.MealPlanning.MealSlotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("day_of_week");

                    b.Property<bool>("IsPrepMeal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_prep_meal");

                    b.Property<Guid>("MealPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("meal_plan_id");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("meal_type");

                    b.Property<string>("PrepNotes")
                        .HasColumnType("text")
                        .HasColumnName("prep_notes");

                    b.Property<Guid?>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<string>("RecipeName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("recipe_name");

                    b.Property<int>("Servings")
                        .HasColumnType("integer")
                        .HasColumnName("servings");

                    b.HasKey("Id")
                        .HasName("pk_meal_slots");

                    b.HasIndex("RecipeId")
                        .HasDatabaseName("ix_meal_slots_recipe_id");

                    b.HasIndex("MealPlanId", "DayOfWeek", "MealType")
                        .HasDatabaseName("ix_meal_slots_meal_plan_id_day_of_week_meal_type");

                    b.ToTable("meal_slots", (string)null);
                });

            modelBuilder.Entity("MealPrepPlanner.Dal.Entities.Pantry.PantryItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly>("DateAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("date_added")
                        .HasDefaultValueSql("current_date");

                    b.Property<DateOnly?>("ExpiresAt")
                        .HasColumnType("date")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingredient_id");

                    b.Property<decimal>("QuantityAmount")
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("quantity");

                    b.Property<string>("QuantityUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("available")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_pantry_items");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_pantry_items_expires_at");

                    b.HasIndex("IngredientId")
                        .HasDatabaseName("ix_pantry_items_ingredient_id");

                    b.HasIndex("HouseholdId", "Status")
                        .HasDatabaseName("ix_pantry_items_household_id_status");

                    b.ToTable("pantry_items", (string)null);
                });

            modelBuilder.Entity("MealPrepPlanner.Dal.Entities.Recipes.IngredientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("Allergens")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("allergens")
                        .HasDefaultValueSql("ARRAY[]::text[]");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DefaultUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("default_unit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<NpgsqlTsVector>("NameTsv")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("name_tsv")
                        .HasAnnotation("Npgsql:TsVectorConfig", "english")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "Name" });

                    b.Property<string>("NutritionPer100g")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("nutrition_per_100g");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_ingredients");

                    b.HasIndex("Allergens")
                        .HasDatabaseName("ix_ingredients_allergens");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Allergens"), "gin");

                    b.HasIndex("NameTsv")
                        .HasDatabaseName("ix_ingredients_name_tsv_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("NameTsv"), "gin");

                    b.ToTable("ingredients", (string)null);
                });

            modelBuilder.Entity("MealPrepPlanner.Dal.Entities.Recipes.RecipeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BaseServings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2)
                        .HasColumnName("base_servings");

                    b.Property<int>("CookTimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("cook_time_minutes");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.PrimitiveCollection<string[]>("EquipmentNeeded")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("equipment_needed")
                        .HasDefaultValueSql("ARRAY[]::text[]");

                    b.PrimitiveCollection<string[]>("Instructions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("instructions");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("PrepTimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("prep_time_minutes");

                    b.Property<NpgsqlTsVector>("SearchTsv")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_tsv")
                        .HasAnnotation("Npgsql:TsVectorConfig", "english")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "Name", "Description" });

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("tags")
                        .HasDefaultValueSql("ARRAY[]::text[]");

                    b.Property<int>("TotalTimeMinutes")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasColumnName("total_time_minutes")
                        .HasComputedColumnSql("\"prep_time_minutes\" + \"cook_time_minutes\"", true);

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_recipes");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_recipes_created_by");

                    b.HasIndex("EquipmentNeeded")
                        .HasDatabaseName("ix_recipes_equipment_needed");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("EquipmentNeeded"), "gin");

                    b.HasIndex("SearchTsv")
                        .HasDatabaseName("ix_recipes_search_tsv_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchTsv"), "gin");

                    b.HasIndex("Tags")
                        .HasDatabaseName("ix_recipes_tags");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Tags"), "gin");

                    b.ToTable("recipes", (string)null);
                });

            modelBuilder.Entity("MealPrepPlanner.Dal.Entities.Recipes.RecipeIngredientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingredient_id");

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ingredient_name_snapshot");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("boolean")
                        .HasColumnName("is_optional");

                    b.Property<string>("Preparation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("preparation");

                    b.Property<decimal>("QuantityAmount")
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("quantity");

                    b.Property<string>("QuantityUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.HasKey("Id")
                        .HasName("pk_recipe_ingredients");

                    b.HasIndex("IngredientId")
                        .HasDatabaseName("ix_recipe_ingredients_ingredient_id");

                    b.HasIndex("RecipeId")
                        .HasDatabaseName("ix_recipe_ingredients_recipe_id");

                    b.ToTable("recipe_ingredients", (string)null);
                });

            modelBuilder.Entity("MealPrepPlanner.Dal.Entities.Shopping.ShoppingListEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("EUR")
                        .HasColumnName("currency");

                    b.Property<decimal?>("EstimatedTotalCost")
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("estimated_total_cost");

                    b.Property<Guid>("MealPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("meal_plan_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<Guid?>("SupermarketId")
                        .HasColumnType("uuid")
                        .HasColumnName("supermarket_id");

                    b.HasKey("Id")
                        .HasName("pk_shopping_lists");

                    b.HasIndex("MealPlanId")
                        .HasDatabaseName("ix_shopping_lists_meal_plan_id");

                    b.HasIndex("SupermarketId")
                        .HasDatabaseName("ix_shopping_lists_supermarket_id");

                    b.ToTable("shopping_lists", (string)null);
                });

            modelBuilder.Entity("MealPrepPlanner.Dal.Entities.Shopping.ShoppingListItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("EstimatedPriceAmount")
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("estimated_price");

                    b.Property<string>("EstimatedPriceCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("estimated_price_currency");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingredient_id");

                    b.Property<decimal?>("PriceAtPurchaseAmount")
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("price_at_purchase");

                    b.Property<string>("PriceAtPurchaseCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("price_at_purchase_currency");

                    b.Property<bool>("Purchased")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("purchased");

                    b.Property<decimal?>("QuantityNeededAmount")
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("quantity_needed");

                    b.Property<string>("QuantityNeededUnit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("quantity_needed_unit");

                    b.Property<decimal?>("QuantityToBuyAmount")
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("quantity_to_buy");

                    b.Property<string>("QuantityToBuyUnit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("quantity_to_buy_unit");

                    b.Property<Guid>("ShoppingListId")
                        .HasColumnType("uuid")
                        .HasColumnName("shopping_list_id");

                    b.HasKey("Id")
                        .HasName("pk_shopping_list_items");

                    b.HasIndex("IngredientId")
                        .HasDatabaseName("ix_shopping_list_items_ingredient_id");

                    b.HasIndex("ShoppingListId")
                        .HasDatabaseName("ix_shopping_list_items_shopping_list_id");

                    b.ToTable("shopping_list_items", (string)null);
                });

            modelBuilder.Entity("MealPrepPlanner.Dal.Entities.Shopping.SupermarketEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Chain")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("chain");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_supermarkets");

                    b.ToTable("supermarkets", (string)null);
                });

            modelBuilder.Entity("MealPrepPlanner.Dal.Entities.Shopping.SupermarketPriceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("EUR")
                        .HasColumnName("currency");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingredient_id");

                    b.Property<decimal?>("PackageSize")
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("package_size");

                    b.Property<string>("PackageUnit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("package_unit");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("price");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("recorded_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("SupermarketId")
                        .HasColumnType("uuid")
                        .HasColumnName("supermarket_id");

                    b.HasKey("Id")
                        .HasName("pk_supermarket_prices");

                    b.HasIndex("IngredientId")
                        .HasDatabaseName("ix_supermarket_prices_ingredient_id");

                    b.HasIndex("SupermarketId", "IngredientId", "RecordedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_supermarket_prices_supermarket_id_ingredient_id_recorded_at");

                    b.ToTable("supermarket_prices", (string)null);
                });

            modelBuilder.Entity("MealPrepPlanner.Dal.Entities.UserPreferences.HouseholdEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_households");

                    b.ToTable("households", (string)null);
                });

            modelBuilder.Entity("MealPrepPlanner.Dal.Entities.UserPreferences.HouseholdMemberEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActivityLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("activity_level");

                    b.Property<int>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("age");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("HeightCm")
                        .HasColumnType("integer")
                        .HasColumnName("height_cm");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("sex");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id")
                        .HasName("pk_household_members");

                    b.HasIndex("HouseholdId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_household_members_household_id_name");

                    b.ToTable("household_members", null, t =>
                        {
                            t.HasCheckConstraint("ck_household_members_age_positive", "\"age\" > 0");
                        });
                });

            modelBuilder.Entity("MealPrepPlanner.Dal.Entities.UserPreferences.PreferencesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.PrimitiveCollection<string[]>("DietaryRestrictions")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("dietary_restrictions")
                        .HasDefaultValueSql("ARRAY[]::text[]");

                    b.PrimitiveCollection<string[]>("Equipment")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("equipment")
                        .HasDefaultValueSql("ARRAY[]::text[]");

                    b.Property<string>("FoodPreferences")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("food_preferences")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<int>("MaxCookingTimeMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(60)
                        .HasColumnName("max_cooking_time_minutes");

                    b.Property<string>("NutritionGoals")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("nutrition_goals")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.PrimitiveCollection<string[]>("PreferredSupermarkets")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("preferred_supermarkets")
                        .HasDefaultValueSql("ARRAY[]::text[]");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("WeeklyBudgetAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(8,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("weekly_budget_amount");

                    b.Property<string>("WeeklyBudgetCurrency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("EUR")
                        .HasColumnName("weekly_budget_currency");

                    b.HasKey("Id")
                        .HasName("pk_preferences");

                    b.HasIndex("DietaryRestrictions")
                        .HasDatabaseName("ix_preferences_dietary_restrictions");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("DietaryRestrictions"), "gin");

                    b.HasIndex("FoodPreferences")
                        .HasDatabaseName("ix_preferences_food_preferences_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("FoodPreferences"), "gin");

                    b.HasIndex("HouseholdId")
                        .IsUnique()
                        .HasDatabaseName("ix_preferences_household_id");

                    b.ToTable("preferences", (string)null);
                });

            modelBuilder.Entity("MealPrepPlanner.Dal.Entities.Audit.DecisionEventEntity", b =>
                {
                    b.HasOne("MealPrepPlanner.Dal.Entities.Audit.DecisionEventEntity", null)
                        .WithMany()
                        .HasForeignKey("ParentDecisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_decision_events_decision_events_parent_decision_id");
                });

            modelBuilder.Entity("MealPrepPlanner.Dal.Entities.MealPlanning.MealPlanEntity", b =>
                {
                    b.HasOne("MealPrepPlanner.Dal.Entities.UserPreferences.HouseholdEntity", null)
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_meal_plans_households_household_id");
                });

            modelBuilder.Entity("MealPrepPlanner.Dal.Entities.MealPlanning.MealSlotEntity", b =>
                {
                    b.HasOne("MealPrepPlanner.Dal.Entities.MealPlanning.MealPlanEntity", null)
                        .WithMany("Slots")
                        .HasForeignKey("MealPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_meal_slots_meal_plans_meal_plan_id");

                    b.HasOne("MealPrepPlanner.Dal.Entities.Recipes.RecipeEntity", null)
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_meal_slots_recipes_recipe_id");
                });

            modelBuilder.Entity("MealPrepPlanner.Dal.Entities.Pantry.PantryItemEntity", b =>
                {
                    b.HasOne("MealPrepPlanner.Dal.Entities.UserPreferences.HouseholdEntity", null)
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pantry_items_households_household_id");

                    b.HasOne("MealPrepPlanner.Dal.Entities.Recipes.IngredientEntity", null)
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pantry_items_ingredients_ingredient_id");
                });

            modelBuilder.Entity("MealPrepPlanner.Dal.Entities.Recipes.RecipeEntity", b =>
                {
                    b.HasOne("MealPrepPlanner.Dal.Entities.UserPreferences.HouseholdEntity", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_recipes_households_created_by");
                });

            modelBuilder.Entity("MealPrepPlanner.Dal.Entities.Recipes.RecipeIngredientEntity", b =>
                {
                    b.HasOne("MealPrepPlanner.Dal.Entities.Recipes.IngredientEntity", null)
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_ingredients_ingredients_ingredient_id");

                    b.HasOne("MealPrepPlanner.Dal.Entities.Recipes.RecipeEntity", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_ingredients_recipes_recipe_id");
                });

            modelBuilder.Entity("MealPrepPlanner.Dal.Entities.Shopping.ShoppingListEntity", b =>
                {
                    b.HasOne("MealPrepPlanner.Dal.Entities.MealPlanning.MealPlanEntity", null)
                        .WithMany()
                        .HasForeignKey("MealPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shopping_lists_meal_plans_meal_plan_id");

                    b.HasOne("MealPrepPlanner.Dal.Entities.Shopping.SupermarketEntity", null)
                        .WithMany()
                        .HasForeignKey("SupermarketId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_shopping_lists_supermarkets_supermarket_id");
                });

            modelBuilder.Entity("MealPrepPlanner.Dal.Entities.Shopping.ShoppingListItemEntity", b =>
                {
                    b.HasOne("MealPrepPlanner.Dal.Entities.Recipes.IngredientEntity", null)
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shopping_list_items_ingredients_ingredient_id");

                    b.HasOne("MealPrepPlanner.Dal.Entities.Shopping.ShoppingListEntity", null)
                        .WithMany("Items")
                        .HasForeignKey("ShoppingListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shopping_list_items_shopping_lists_shopping_list_id");
                });

            modelBuilder.Entity("MealPrepPlanner.Dal.Entities.Shopping.SupermarketPriceEntity", b =>
                {
                    b.HasOne("MealPrepPlanner.Dal.Entities.Recipes.IngredientEntity", null)
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_supermarket_prices_ingredients_ingredient_id");

                    b.HasOne("MealPrepPlanner.Dal.Entities.Shopping.SupermarketEntity", null)
                        .WithMany()
                        .HasForeignKey("SupermarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_supermarket_prices_supermarkets_supermarket_id");
                });

            modelBuilder.Entity("MealPrepPlanner.Dal.Entities.UserPreferences.HouseholdMemberEntity", b =>
                {
                    b.HasOne("MealPrepPlanner.Dal.Entities.UserPreferences.HouseholdEntity", null)
                        .WithMany("Members")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_household_members_households_household_id");
                });

            modelBuilder.Entity("MealPrepPlanner.Dal.Entities.UserPreferences.PreferencesEntity", b =>
                {
                    b.HasOne("MealPrepPlanner.Dal.Entities.UserPreferences.HouseholdEntity", null)
                        .WithOne("Preferences")
                        .HasForeignKey("MealPrepPlanner.Dal.Entities.UserPreferences.PreferencesEntity", "HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_preferences_households_household_id");
                });

            modelBuilder.Entity("MealPrepPlanner.Dal.Entities.MealPlanning.MealPlanEntity", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("MealPrepPlanner.Dal.Entities.Recipes.RecipeEntity", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("MealPrepPlanner.Dal.Entities.Shopping.ShoppingListEntity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MealPrepPlanner.Dal.Entities.UserPreferences.HouseholdEntity", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Preferences");
                });
#pragma warning restore 612, 618
        }
    }
}
